package net.runelite.client.plugins.geautotrader;

public enum GeReasonCode
{
	OK,
	STOPPED_F8,
	DISABLED,
	GAME_NOT_LOGGED_IN,
	WORLD_NOT_F2P,
	LOGIN_RESYNC,
	GE_NOT_OPEN,
	BLOCKER_ACTIVE,
	SLOT_IDENTITY_CHANGED,
	SETUP_NOT_OPEN,
	SETUP_ITEM_MISMATCH,
	SETUP_QUANTITY_MISMATCH,
	SETUP_PRICE_MISMATCH,
	SETUP_SIDE_MISMATCH,
	UI_STATE_TIMEOUT,
	CONFIRM_STATE_TIMEOUT,
	COLLECT_STATE_MISMATCH,
	INVENTORY_MISMATCH,
	INSUFFICIENT_GP,
	BUY_LIMIT_EXHAUSTED,
	MARKET_DATA_UNAVAILABLE,
	MARKET_DATA_STALE,
	NO_OPPORTUNITY,
	EXECUTION_TARGET_UNAVAILABLE,
	EXECUTION_REJECTED
}
