package net.runelite.client.plugins.geautotrader;

public enum GeTradePhase
{
	IDLE,
	WAIT_BUY_SETUP,
	WAIT_SEARCH_RESULTS,
	WAIT_ITEM_SELECTED,
	WAIT_QUANTITY_PROMPT,
	WAIT_QUANTITY_VALUE,
	WAIT_PRICE_PROMPT,
	WAIT_PRICE_VALUE,
	WAIT_BUY_SLOT,
	MONITOR_BUY,
	WAIT_ABORT_READY,
	WAIT_ABORT_RESULT,
	WAIT_BUY_COLLECT_READY,
	WAIT_BUY_COLLECT_RESULT,
	WAIT_SELL_SETUP,
	WAIT_SELL_ITEM_SELECTED,
	WAIT_SELL_QUANTITY_PROMPT,
	WAIT_SELL_QUANTITY_VALUE,
	WAIT_SELL_PRICE_PROMPT,
	WAIT_SELL_PRICE_VALUE,
	WAIT_SELL_SLOT,
	MONITOR_SELL,
	WAIT_SELL_COLLECT_READY,
	WAIT_SELL_COLLECT_RESULT
}
